-- Initialize schema for Explainable Commute Delay Predictor

-- 1. Routes Table
CREATE TABLE IF NOT EXISTS routes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    origin TEXT NOT NULL,
    destination TEXT NOT NULL,
    path_variants JSONB
);

-- 2. Saved Routes Table
CREATE TABLE IF NOT EXISTS saved_routes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    route_id UUID NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
    nickname TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Traffic Logs Table (high-volume logging)
CREATE TABLE IF NOT EXISTS traffic_logs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    route_id UUID REFERENCES routes(id) ON DELETE CASCADE,
    path_variant TEXT,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    travel_time_min NUMERIC NOT NULL,
    distance_km NUMERIC NOT NULL
);

-- 4. Weather Logs Table (high-volume logging)
CREATE TABLE IF NOT EXISTS weather_logs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
    rainfall_mm NUMERIC,
    temperature NUMERIC,
    condition TEXT,
    visibility NUMERIC
);

-- 5. Events Table
CREATE TABLE IF NOT EXISTS events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    date DATE NOT NULL,
    route_ids_affected UUID[],
    event_type TEXT,
    distance_to_route_km NUMERIC
);

-- 6. Prediction History Table
CREATE TABLE IF NOT EXISTS prediction_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    route_id UUID REFERENCES routes(id) ON DELETE CASCADE,
    requested_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    predicted_delay NUMERIC NOT NULL,
    shap_breakdown JSONB,
    actual_delay NUMERIC
);

-- Row Level Security (RLS)
ALTER TABLE saved_routes ENABLE ROW LEVEL SECURITY;
ALTER TABLE prediction_history ENABLE ROW LEVEL SECURITY;

-- RLS Policies for saved_routes
CREATE POLICY "Users can select their own saved routes"
ON saved_routes FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own saved routes"
ON saved_routes FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own saved routes"
ON saved_routes FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own saved routes"
ON saved_routes FOR DELETE
TO authenticated
USING (auth.uid() = user_id);

-- RLS Policies for prediction_history
CREATE POLICY "Users can select their own prediction history"
ON prediction_history FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own prediction history"
ON prediction_history FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own prediction history"
ON prediction_history FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own prediction history"
ON prediction_history FOR DELETE
TO authenticated
USING (auth.uid() = user_id);
